### ISSUE TITLE
job.status does not work

### ISSUE THREAD

**Issue by nonhermitian** [qiskit-community/qiskit-aqt-provider#37]
### Informations

- **Qiskit AQT Provider version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```
Traceback (most recent call last):
  File "<ipython-input-5-0b8abe45e471>", line 1, in <module>
    job.status()
  File "/Users/paul/Desktop/GitHub/qiskit-aqt-provider/qiskit/providers/aqt/aqt_job.py", line 168, in status
    return result['status']
TypeError: 'Response' object is not subscriptable
```

**Comment by nonhermitian** [comment]
A simple fix
